export const AFRICAN_CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Bénin": ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Bohicon", "Natitingou", "Ouidah"],
  "Côte d’Ivoire": ["Abidjan", "Yamoussoukro", "Bouaké", "San-Pédro", "Korhogo", "Daloa", "Man"],
  "Sénégal": ["Dakar", "Thiès", "Saint-Louis", "Touba", "Kaolack", "Ziguinchor", "Mbour"],
  "Cameroun": ["Douala", "Yaoundé", "Bafoussam", "Garoua", "Bamenda", "Maroua", "Kribi"],
  "Togo": ["Lomé", "Kara", "Sokodé", "Kpalimé", "Atakpamé", "Dapaong"],
  "Nigeria": ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Kano", "Enugu", "Benin City"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast", "Tema"],
  "Maroc": ["Casablanca", "Rabat", "Marrakech", "Tanger", "Fès", "Agadir"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi", "Musanze", "Gitarama"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem"],
  "Congo": ["Brazzaville", "Pointe-Noire", "Dolisie"],
  "République démocratique du Congo": ["Kinshasa", "Lubumbashi", "Goma", "Kisangani", "Bukavu", "Mbuji-Mayi"],
  "Mali": ["Bamako", "Sikasso", "Mopti", "Ségou", "Kayes"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora"],
  "Guinée": ["Conakry", "Kankan", "Kindia", "Labé", "Nzérékoré"],
  "Niger": ["Niamey", "Zinder", "Maradi", "Tahoua", "Agadez"],
  "Tchad": ["N'Djamena", "Moundou", "Sarh", "Abéché"],
  "Tunisie": ["Tunis", "Sfax", "Sousse", "Bizerte"],
  "Algérie": ["Alger", "Oran", "Constantine", "Annaba"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  "Afrique du Sud": ["Johannesburg", "Le Cap", "Durban", "Pretoria", "Port Elizabeth"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga"],
  "Maurice": ["Port-Louis", "Beau-Bassin Rose-Hill", "Vacoas", "Curepipe"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela"],
  "Égypte": ["Le Caire", "Alexandrie", "Gizeh", "Louxor", "Assouan"],
  "Éthiopie": ["Addis-Abeba", "Dire Dawa", "Mekele", "Gondar"],
  "Ouganda": ["Kampala", "Entebbe", "Gulu", "Jinja"],
  "Tanzanie": ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza", "Zanzibar"],
  "Zambie": ["Lusaka", "Kitwe", "Ndola", "Livingstone"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare"],
  "Mauritanie": ["Nouakchott", "Nouadhibou", "Kiffa", "Rosso"],
  "Centrafrique": ["Bangui", "Bimbo", "Berbérati"],
  "Comores": ["Moroni", "Mutsamudu", "Fomboni"],
  "Djibouti": ["Djibouti", "Ali Sabieh", "Tadjourah"],
  "Guinée équatoriale": ["Malabo", "Bata", "Oyala"],
  "Guinée-Bissau": ["Bissau", "Bafatá", "Gabú"],
  "Cap-Vert": ["Praia", "Mindelo", "Santa Maria"],
  "Burundi": ["Bujumbura", "Gitega", "Ngozi"],
  "Botswana": ["Gaborone", "Francistown", "Molepolole"],
  "Namibie": ["Windhoek", "Walvis Bay", "Swakopmund"],
  "Liberia": ["Monrovia", "Gbarnga", "Kakata"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema"],
  "Gambie": ["Banjul", "Serekunda", "Brikama"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula"]
};

export function getCitiesForCountry(countryName: string): string[] {
  if (!countryName) return [];
  return AFRICAN_CITIES_BY_COUNTRY[countryName] || [];
}
