import { getSupabaseAdmin } from "@/lib/supabase-admin";

export async function getPaidJobsUnlock(userId: string, offerId: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, unlocked: false }; const { data, error } = await supabase.from("jobs_unlocks").select("id").eq("user_id", userId).eq("offer_id", offerId).eq("status", "paid").maybeSingle(); if (error) return { configured: true as const, unlocked: false, error }; return { configured: true as const, unlocked: Boolean(data) }; }
export async function createPendingJobsUnlock(userId: string, offerId: string, paymentId: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, unlock: null }; const { data, error } = await supabase.from("jobs_unlocks").upsert({ user_id: userId, offer_id: offerId, amount_xof: 200, provider: "moneroo", provider_payment_id: paymentId, status: "pending" }, { onConflict: "user_id,offer_id" }).select().single(); if (error) return { configured: true as const, unlock: null, error }; return { configured: true as const, unlock: data }; }
export async function getJobsUnlockById(userId: string, unlockId: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, unlock: null }; const { data, error } = await supabase.from("jobs_unlocks").select("id,status,provider_payment_id").eq("id", unlockId).eq("user_id", userId).maybeSingle(); if (error) return { configured: true as const, unlock: null, error }; return { configured: true as const, unlock: data }; }
export async function activateJobsUnlockByPayment(userId: string, paymentId: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, unlocked: false }; const { data, error } = await supabase.from("jobs_unlocks").update({ status: "paid", paid_at: new Date().toISOString() }).eq("user_id", userId).eq("provider_payment_id", paymentId).in("status", ["pending", "paid"]).select().maybeSingle(); if (error) return { configured: true as const, unlocked: false, error }; return { configured: true as const, unlocked: Boolean(data) }; }

const subscriptionCodes: Record<string, { code: string; hours?: number; days?: number }> = { "jobs-candidate-24h": { code: "candidate_24h", hours: 24 }, "jobs-candidate-week": { code: "candidate_week", days: 7 }, "jobs-candidate-month": { code: "candidate_month", days: 30 }, "jobs-employer-post": { code: "employer_post" }, "jobs-employer-week": { code: "employer_week", days: 7 }, "jobs-employer-month": { code: "employer_month", days: 30 } };
export async function createPendingJobsSubscription(userId: string, audience: "candidate" | "employer", planId: string, amount: number, paymentId: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, subscription: null }; const plan = subscriptionCodes[planId]; if (!plan) return { configured: true as const, subscription: null, error: new Error("Plan Jobs invalide") }; const { data, error } = await supabase.from("jobs_subscriptions").insert({ user_id: userId, audience, plan_code: plan.code, amount_xof: amount, provider: "moneroo", provider_payment_id: paymentId, status: "pending" }).select().single(); if (error) return { configured: true as const, subscription: null, error }; return { configured: true as const, subscription: data }; }
export async function getJobsSubscriptionById(userId: string, id: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, subscription: null }; const { data, error } = await supabase.from("jobs_subscriptions").select("id,status,plan_code,provider_payment_id").eq("id", id).eq("user_id", userId).maybeSingle(); if (error) return { configured: true as const, subscription: null, error }; return { configured: true as const, subscription: data }; }
export async function activateJobsSubscription(userId: string, id: string) { const supabase = getSupabaseAdmin(); if (!supabase) return { configured: false as const, active: false }; const { data: subscription, error: readError } = await supabase.from("jobs_subscriptions").select("plan_code").eq("id", id).eq("user_id", userId).maybeSingle(); if (readError || !subscription) return { configured: true as const, active: false }; const now = new Date(); const plan = Object.values(subscriptionCodes).find((item) => item.code === subscription.plan_code); const end = plan?.hours ? new Date(now.getTime() + plan.hours * 3600000) : plan?.days ? new Date(now.getTime() + plan.days * 86400000) : null; const { data, error } = await supabase.from("jobs_subscriptions").update({ status: "active", starts_at: now.toISOString(), ends_at: end?.toISOString() ?? null }).eq("id", id).eq("user_id", userId).select().maybeSingle(); if (error) return { configured: true as const, active: false, error }; return { configured: true as const, active: Boolean(data) }; }
