export type MarketplaceProduct = {
  id: string;
  title: string;
  supplier: string;
  country: string;
  city: string;
  category: string;
  priceXof: number;
  image: string;
  accent: string;
  certified: boolean;
  boosted: boolean;
  installment: boolean;
  months: number;
  description: string;
};

export const marketplaceSeed: MarketplaceProduct[] = [
  { id: "seed-karite", title: "Beurre de karité brut premium — 25 kg", supplier: "Coopérative Naya Naturals", country: "BJ", city: "Parakou", category: "Beauté & bien-être", priceXof: 185000, image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80", accent: "#b78238", certified: true, boosted: true, installment: true, months: 6, description: "Beurre de karité collecté et conditionné au Bénin, destiné aux marques et laboratoires." },
  { id: "seed-wax", title: "Wax imprimé artisanal — collection Harmattan", supplier: "Atelier Kora Textiles", country: "CI", city: "Abidjan", category: "Mode & textile", priceXof: 32000, image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=80", accent: "#9e001f", certified: true, boosted: true, installment: false, months: 0, description: "Série limitée de tissus imprimés pour créateurs, boutiques et maisons de mode." },
  { id: "seed-cafe", title: "Café arabica torréfié — carton de 12", supplier: "Monts du Cameroun Coffee", country: "CM", city: "Bafoussam", category: "Alimentation", priceXof: 78000, image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80", accent: "#5b3924", certified: false, boosted: false, installment: true, months: 3, description: "Café arabica de montagne, torréfaction moyenne et traçabilité par lot." },
  { id: "seed-basket", title: "Paniers tressés à la main — lot de 20", supplier: "Maison Sira Artisanat", country: "BF", city: "Ouagadougou", category: "Maison & artisanat", priceXof: 94000, image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80", accent: "#d16a2a", certified: true, boosted: false, installment: false, months: 0, description: "Paniers durables réalisés par des artisanes locales, pour décoration et distribution." },
  { id: "seed-moringa", title: "Poudre de moringa bio — 10 kg", supplier: "Green Sahel Organics", country: "SN", city: "Thiès", category: "Alimentation", priceXof: 125000, image: "https://images.unsplash.com/photo-1515586000433-45406d8e6662?auto=format&fit=crop&w=900&q=80", accent: "#3b6b4d", certified: false, boosted: false, installment: true, months: 4, description: "Moringa séché à basse température, conditionnement professionnel et fiches de lot." },
  { id: "seed-leather", title: "Petite maroquinerie en cuir — série entreprise", supplier: "Bamako Leather Studio", country: "ML", city: "Bamako", category: "Mode & textile", priceXof: 215000, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", accent: "#7a4a36", certified: true, boosted: false, installment: true, months: 12, description: "Objets personnalisables pour cadeaux d’entreprise et revendeurs spécialisés." },
  { id: "seed-solar", title: "Kit solaire domestique — 120 W", supplier: "Sun Africa Solutions", country: "TG", city: "Lomé", category: "Énergie", priceXof: 169000, image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80", accent: "#c68a00", certified: true, boosted: true, installment: true, months: 12, description: "Kit solaire avec panneau, batterie et éclairage pour petites activités et foyers." },
  { id: "seed-cocoa", title: "Fèves de cacao fermentées — sac de 50 kg", supplier: "Alliance Cacao Durable", country: "CI", city: "Daloa", category: "Alimentation", priceXof: 260000, image: "https://images.unsplash.com/photo-1575377427642-087cf684f04d?auto=format&fit=crop&w=900&q=80", accent: "#6d4327", certified: false, boosted: false, installment: true, months: 6, description: "Cacao de terroir pour chocolatiers, avec origine producteur et contrôle qualité." },
  { id: "seed-honey", title: "Miel de forêt naturel — cartons professionnels", supplier: "Ruche du Bénin", country: "BJ", city: "Natitingou", category: "Alimentation", priceXof: 68000, image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=900&q=80", accent: "#d39b21", certified: true, boosted: false, installment: false, months: 0, description: "Miel brut récolté auprès de petits apiculteurs et conditionné pour boutiques et hôtels." },
  { id: "seed-soap", title: "Savons artisanaux au neem — lot revendeur", supplier: "Terre & Sève", country: "TG", city: "Kara", category: "Beauté & bien-être", priceXof: 56000, image: "https://images.unsplash.com/photo-1607006483225-7c9a0d6b1c5e?auto=format&fit=crop&w=900&q=80", accent: "#527c54", certified: false, boosted: true, installment: false, months: 0, description: "Savons solides fabriqués localement, formulation naturelle et emballage prêt à vendre." },
  { id: "seed-ceramics", title: "Vaisselle en terre cuite — collection restaurant", supplier: "Atelier Koudougou", country: "BF", city: "Koudougou", category: "Maison & artisanat", priceXof: 148000, image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=80", accent: "#a65f38", certified: true, boosted: false, installment: true, months: 3, description: "Pièces durables et personnalisables pour restaurants, hôtels et concept stores." },
  { id: "seed-furniture", title: "Mobilier bambou — salon professionnel", supplier: "Bambou Design Rwanda", country: "RW", city: "Kigali", category: "Maison & artisanat", priceXof: 480000, image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=900&q=80", accent: "#6a7b45", certified: true, boosted: true, installment: true, months: 12, description: "Mobilier en bambou issu de filières responsables, pour bureaux et espaces d’accueil." },
  { id: "seed-phone", title: "Accessoires mobiles reconditionnés — lot de 50", supplier: "Lagos Tech Supply", country: "NG", city: "Lagos", category: "Technologie", priceXof: 375000, image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=900&q=80", accent: "#355070", certified: false, boosted: false, installment: true, months: 6, description: "Lots vérifiés pour revendeurs, avec inventaire et contrôle qualité à la réception." },
  { id: "seed-shea-oil", title: "Huile de karité cosmétique — bidons de 20 L", supplier: "Naya Naturals Export", country: "BJ", city: "Cotonou", category: "Beauté & bien-être", priceXof: 235000, image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=900&q=80", accent: "#b78238", certified: true, boosted: false, installment: true, months: 6, description: "Huile filtrée pour laboratoires et marques cosmétiques, avec traçabilité par lot." },
  { id: "seed-solar-pro", title: "Éclairage solaire pour boutique — pack 10", supplier: "Sun Africa Solutions", country: "TG", city: "Lomé", category: "Énergie", priceXof: 295000, image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80", accent: "#c68a00", certified: true, boosted: false, installment: true, months: 12, description: "Pack d’éclairage solaire pour commerces et ateliers, installation accompagnée." },
  ];

export const marketplaceCategories = ["Toutes les catégories", "Magazines & médias", "Alimentation", "Beauté & bien-être", "Mode & textile", "Maison & artisanat", "Énergie", "Technologie"];
