import fs from "fs";
import path from "path";
import { v4 as uuid } from "uuid";

const FILE = path.join(process.cwd(), "src", "data", "wab.json");
export type WabPost = { id: string; author: string; authorAvatarUrl?: string; authorUserId?: string; pageId?: string; groupId?: string; visibility?: "public" | "community" | "group"; audience?: { countries?: string[]; industries?: string[] }; pageName?: string; pageLogoUrl?: string; publisherName?: string; headline: string; location: string; content: string; type: "text" | "opportunity" | "document" | "video" | "marketplace_product"; media?: Array<{ path: string; mimeType: string; name: string; size?: number }>; tags: string[]; views: number; watchSeconds: number; likes: number; comments: number; shares: number; isBoosted: boolean; boostEndsAt?: string; sourceType?: "jobs_offer" | "jobs_candidate" | "crowdfunding_project" | "marketplace_product"; sourceId?: string; sourceUrl?: string; sourceTitle?: string; createdAt: string; moderationStatus: "published" | "pending_review" | "hidden"; };
export type WabPage = { id: string; ownerUserId: string; name: string; slug: string; logoUrl?: string; description?: string; status: "active" | "archived"; createdAt: string; updatedAt: string };
export type WabGroup = { id: string; ownerUserId: string; name: string; slug: string; description?: string; logoUrl?: string; privacy: "community" | "private"; status: "active" | "archived"; createdAt: string; updatedAt: string };
export type WabGroupMember = { groupId: string; userId: string; role: "owner" | "moderator" | "member"; status: "active" | "pending" | "blocked"; createdAt: string };
export type WabProfile = { id: string; userId: string; fullName: string; headline: string; about: string; companyName?: string; industry?: string; country: string; city?: string; status: "active" | "silent" | "banned"; createdAt: string; updatedAt: string; };
export type WabReaction = { postId: string; userId: string; createdAt: string };
export type WabComment = { id: string; postId: string; userId: string; author: string; content: string; status: "published" | "hidden"; createdAt: string };
export type WabReport = { id: string; targetType: "post" | "profile"; targetId: string; reporterId: string; reason: string; status: "open" | "reviewing" | "resolved" | "dismissed"; createdAt: string };
export type WabView = { postId: string; userId?: string; visitorId?: string; watchSeconds: number; createdAt: string };
export type WabReward = { id: string; userId: string; postId: string; type: "views_1000" | "watch_minutes_3000"; threshold: number; amount: number; status: "pending_review" | "validated" | "rejected" | "paid"; createdAt: string; validatedAt?: string; paidAt?: string };
export type WabSalon = { id: string; hostUserId: string; host: string; title: string; description: string; startsAt: string; endsAt?: string; status: "scheduled" | "live" | "ended" | "cancelled"; replayUrl?: string; participants: number; createdAt: string };
export type WabSalonParticipant = { salonId: string; userId: string; name: string; joinedAt: string };
export type WabSalonMessage = { id: string; salonId: string; userId: string; author: string; content: string; createdAt: string };
export type WabBoost = { id: string; postId: string; userId: string; budgetXof: number; durationDays: number; audienceType?: "community" | "public"; targetCountries: string[]; targetIndustries: string[]; paymentId?: string; status: "pending" | "active" | "ended" | "cancelled" | "failed"; startsAt?: string; endsAt?: string; createdAt: string };
export type WabConnection = { followerUserId: string; profileId: string; createdAt: string };
export type WabNotification = { id: string; userId: string; type: string; title: string; body: string; href?: string; readAt?: string; createdAt: string };
export type WabStory = { id: string; author: string; authorUserId?: string; avatarUrl?: string; mediaUrl: string; mimeType: string; caption?: string; createdAt: string; expiresAt: string; views: number; likes: number; moderationStatus: "published" | "pending_review" | "hidden" };
export type WabReel = { id: string; author: string; authorUserId?: string; avatarUrl?: string; mediaUrl: string; mimeType: string; caption: string; createdAt: string; views: number; likes: number; moderationStatus: "published" | "pending_review" | "hidden" };
export type WabDatabase = { posts: WabPost[]; pages: WabPage[]; groups: WabGroup[]; groupMembers: WabGroupMember[]; profiles: WabProfile[]; reactions: WabReaction[]; comments: WabComment[]; reports: WabReport[]; views: WabView[]; rewards: WabReward[]; stories: WabStory[]; reels: WabReel[]; salons: WabSalon[]; salonParticipants: WabSalonParticipant[]; salonMessages: WabSalonMessage[]; boosts: WabBoost[]; connections: WabConnection[]; notifications: WabNotification[] };
const seed: WabPost[] = [
 { id: "wab-1", author: "Aïcha Bamba", authorAvatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=160&auto=format&fit=crop", headline: "Fondatrice · Abidjan Green Logistics", location: "Abidjan, Côte d’Ivoire", content: "Nous ouvrons notre programme de partenaires pour accélérer la logistique urbaine durable en Afrique de l’Ouest. Nous recherchons des opérateurs, investisseurs et experts de la chaîne du froid.", type: "opportunity", tags: ["Logistique", "Partenariat", "Côte d’Ivoire"], views: 1840, watchSeconds: 0, likes: 126, comments: 18, shares: 0, isBoosted: true, createdAt: "2026-08-15T08:00:00.000Z", moderationStatus: "published" },
 { id: "wab-2", author: "Moussa Diallo", authorAvatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop", headline: "Consultant finance & stratégie", location: "Dakar, Sénégal", content: "Trois leviers concrets pour rendre une PME exportatrice : une offre normalisée, une logistique tracée et une stratégie de paiement adaptée à chaque marché cible.", type: "text", tags: ["PME", "Export", "Finance"], views: 960, watchSeconds: 0, likes: 74, comments: 9, shares: 0, isBoosted: false, createdAt: "2026-08-15T07:20:00.000Z", moderationStatus: "published" },
 { id: "wab-3", author: "Njeri Wanjiku", authorAvatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop", headline: "Product Lead · Fintech Africa", location: "Nairobi, Kenya", content: "Retour sur notre étude des parcours de paiement des entrepreneurs africains. Le document présente les usages et recommandations pour les plateformes B2B régionales.", type: "document", tags: ["Fintech", "Étude", "Paiement"], views: 1204, watchSeconds: 0, likes: 103, comments: 22, shares: 0, isBoosted: false, createdAt: "2026-08-14T18:00:00.000Z", moderationStatus: "published" }
];
const demoStories: WabStory[] = [
  { id: "story-demo-aicha", author: "Aïcha Bamba", avatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=160&auto=format&fit=crop", mediaUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&auto=format&fit=crop", mimeType: "image/jpeg", caption: "Notre nouvel espace logistique à Abidjan.", createdAt: "2026-08-17T08:00:00.000Z", expiresAt: "2026-08-18T08:00:00.000Z", views: 238, likes: 28, moderationStatus: "published" },
  { id: "story-demo-moussa", author: "Moussa Diallo", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop", mediaUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&auto=format&fit=crop", mimeType: "image/jpeg", caption: "Session conseil avec les PME exportatrices.", createdAt: "2026-08-17T07:30:00.000Z", expiresAt: "2026-08-18T07:30:00.000Z", views: 184, likes: 19, moderationStatus: "published" },
  { id: "story-demo-njeri", author: "Njeri Wanjiku", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop", mediaUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&auto=format&fit=crop", mimeType: "image/jpeg", caption: "Les équipes fintech préparent la rentrée.", createdAt: "2026-08-17T06:45:00.000Z", expiresAt: "2026-08-18T06:45:00.000Z", views: 321, likes: 42, moderationStatus: "published" }
];
const demoReels: WabReel[] = [
  { id: "reel-demo-1", author: "WAB Business", mediaUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4", mimeType: "video/mp4", caption: "Une idée, un partenaire, une opportunité : le réseau WAB en mouvement.", createdAt: "2026-08-17T08:30:00.000Z", views: 682, likes: 87, moderationStatus: "published" },
  { id: "reel-demo-2", author: "Abidjan Green Logistics", mediaUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4", mimeType: "video/mp4", caption: "Dans les coulisses de la logistique urbaine durable.", createdAt: "2026-08-16T17:00:00.000Z", views: 514, likes: 61, moderationStatus: "published" }
];
function reconcileWabDatabase(database: WabDatabase): WabDatabase {
  const now = Date.now();
  database.stories = database.stories.filter((story) => story.expiresAt && Date.parse(story.expiresAt) > now && story.moderationStatus === "published");
  database.reels = database.reels.filter((reel) => reel.moderationStatus === "published");
  database.boosts.forEach((boost) => { if (boost.status === "active" && boost.endsAt && Date.parse(boost.endsAt) <= now) boost.status = "ended"; });
  database.posts.forEach((post) => { const active = database.boosts.some((boost) => boost.postId === post.id && boost.status === "active" && (!boost.endsAt || Date.parse(boost.endsAt) > now)); post.isBoosted = active || (post.isBoosted && !post.authorUserId); });
  return database;
}

export function readWabDB(): WabDatabase { try { if (!fs.existsSync(FILE)) { fs.mkdirSync(path.dirname(FILE), { recursive: true }); fs.writeFileSync(FILE, JSON.stringify({ posts: seed, pages: [], groups: [], groupMembers: [], profiles: [], reactions: [], comments: [], reports: [], views: [], rewards: [], stories: demoStories, reels: demoReels, salons: [], salonParticipants: [], salonMessages: [], boosts: [], connections: [], notifications: [] }, null, 2)); } const data = JSON.parse(fs.readFileSync(FILE, "utf8")) as Partial<WabDatabase>; return reconcileWabDatabase({ posts: (data.posts ?? seed).map((post) => ({ ...post, shares: Number(post.shares ?? 0) })), pages: data.pages ?? [], groups: data.groups ?? [], groupMembers: data.groupMembers ?? [], profiles: data.profiles ?? [], reactions: data.reactions ?? [], comments: data.comments ?? [], reports: data.reports ?? [], views: data.views ?? [], rewards: data.rewards ?? [], stories: data.stories ?? demoStories, reels: data.reels ?? demoReels, salons: data.salons ?? [], salonParticipants: data.salonParticipants ?? [], salonMessages: data.salonMessages ?? [], boosts: data.boosts ?? [], connections: data.connections ?? [], notifications: data.notifications ?? [] }); } catch { return { posts: seed.map((post) => ({ ...post, shares: Number(post.shares ?? 0) })), pages: [], groups: [], groupMembers: [], profiles: [], reactions: [], comments: [], reports: [], views: [], rewards: [], stories: demoStories, reels: demoReels, salons: [], salonParticipants: [], salonMessages: [], boosts: [], connections: [], notifications: [] }; } }
export function writeWabDB(db: WabDatabase) { fs.mkdirSync(path.dirname(FILE), { recursive: true }); fs.writeFileSync(FILE, JSON.stringify(db, null, 2)); }
export function createWabPost(data: Omit<WabPost, "id" | "views" | "watchSeconds" | "likes" | "comments" | "shares" | "isBoosted" | "createdAt" | "moderationStatus">) { const db = readWabDB(); const post: WabPost = { ...data, id: uuid(), views: 0, watchSeconds: 0, likes: 0, comments: 0, shares: 0, isBoosted: false, createdAt: new Date().toISOString(), moderationStatus: "published" }; db.posts.unshift(post); writeWabDB(db); return post; }
