import { redirect } from "next/navigation";
import { getCurrentUserFromCookie } from "@/lib/auth";
import { readJobsDB } from "@/lib/jobs-db";
import JobsAdminClient from "./JobsAdminClient";

export default async function JobsAdminPage() {
 const user = await getCurrentUserFromCookie(); if (!user || !["admin", "administrateur", "gerant"].includes(user.role)) redirect("/emploi"); const db = readJobsDB(); const activeBoosts = db.boosts.filter((item) => item.status === "active"); const paidUnlocks = db.unlocks.filter((item) => item.status === "paid"); const activeSubscriptions = db.subscriptions.filter((item) => item.status === "active"); const revenue = paidUnlocks.reduce((sum, item) => sum + item.amount, 0) + activeSubscriptions.reduce((sum, item) => sum + item.amount, 0) + activeBoosts.reduce((sum, item) => sum + item.amount, 0);
 return <main className="min-h-screen bg-[#f7f8fa] py-10"><div className="mx-auto max-w-6xl px-5"><p className="text-xs font-bold uppercase tracking-widest text-[#087e8b]">Administration Jobs</p><h1 className="mt-2 font-display text-3xl font-extrabold text-[#071b36]">Pilotage Envol Africa Jobs</h1><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Offres publiées", db.offers.filter((item) => item.status === "published").length], ["Candidatures publiques", db.candidates.length], ["Abonnements actifs", activeSubscriptions.length], ["Revenus confirmés", `${revenue.toLocaleString("fr-FR")} XOF`]].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-2 text-2xl font-extrabold text-[#071b36]">{value}</p></div>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-display text-xl font-extrabold">Contrôles prioritaires</h2><div className="mt-4 space-y-3 text-sm"><p className="rounded-xl bg-slate-50 p-4"><strong>{db.offers.filter((item) => item.status === "draft").length}</strong> offre(s) en brouillon / à modérer</p><p className="rounded-xl bg-slate-50 p-4"><strong>{db.boosts.filter((item) => item.status === "pending").length}</strong> paiement(s) de boost en attente</p><p className="rounded-xl bg-slate-50 p-4"><strong>{db.subscriptions.filter((item) => item.status === "pending").length}</strong> abonnement(s) en attente de confirmation</p></div></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-display text-xl font-extrabold">Performance</h2><div className="mt-4 space-y-3 text-sm"><p className="rounded-xl bg-[#e9f7f5] p-4">Décryptages confirmés : <strong>{paidUnlocks.length}</strong></p><p className="rounded-xl bg-[#fff3dc] p-4">Publications boostées : <strong>{activeBoosts.length}</strong></p><p className="rounded-xl bg-slate-50 p-4">Candidatures envoyées : <strong>{db.applications.length}</strong></p></div></section></div><JobsAdminClient /></div></main>;
}
