"use client";

import { useState } from "react";

const candidatePlans = [{ id: "jobs-candidate-24h", name: "24 heures", price: "500 XOF", note: "Décryptez et postulez sans limite pendant 24 h." }, { id: "jobs-candidate-week", name: "1 semaine", price: "2 000 XOF", note: "Accès complet pendant sept jours.", featured: true }, { id: "jobs-candidate-month", name: "1 mois", price: "5 000 XOF", note: "Le meilleur choix pour votre recherche active." }];
const employerPlans = [{ id: "jobs-employer-post", name: "À la publication", price: "1 000 XOF", note: "Après vos deux offres gratuites." }, { id: "jobs-employer-week", name: "1 semaine", price: "7 000 XOF", note: "Publiez et gérez vos recrutements pendant sept jours." }, { id: "jobs-employer-month", name: "1 mois", price: "22 000 XOF", note: "Publications, suivi complet et magazine numérique du mois.", featured: true }];

export default function SubscriptionsClient() {
  const [audience, setAudience] = useState<"candidate" | "employer">("candidate");
  const [loading, setLoading] = useState<string | null>(null);
  const [error, setError] = useState("");
  const plans = audience === "candidate" ? candidatePlans : employerPlans;
  async function selectPlan(planId: string) {
    setLoading(planId); setError("");
    try { const response = await fetch("/api/jobs/subscriptions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ planId, audience }) }); const data = await response.json(); if (response.status === 401) { window.location.assign(`/auth/login?next=${encodeURIComponent("/emploi/abonnements")}`); return; } if (!response.ok) throw new Error(data.error); window.location.assign(data.checkoutUrl); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur est survenue."); } finally { setLoading(null); }
  }
  return <main className="min-h-screen bg-[#f7f8fa] py-12"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#087e8b]">Envol Africa Jobs</p><h1 className="mt-3 font-display text-4xl font-extrabold text-[#071b36]">L’accès adapté à votre objectif</h1><p className="mt-4 text-slate-600">Choisissez votre accès sécurisé. Les paiements sont traités en XOF par nos moyens de paiement partenaires.</p></div><div className="mx-auto mt-8 flex max-w-md rounded-2xl bg-white p-1 shadow-sm"><button onClick={() => setAudience("candidate")} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold ${audience === "candidate" ? "bg-[#071b36] text-white" : "text-slate-600"}`}>Je cherche un emploi</button><button onClick={() => setAudience("employer")} className={`flex-1 rounded-xl px-4 py-3 text-sm font-bold ${audience === "employer" ? "bg-[#071b36] text-white" : "text-slate-600"}`}>Je recrute</button></div>{error && <p className="mx-auto mt-5 max-w-lg rounded-xl bg-red-50 p-4 text-center text-sm text-red-800">{error}</p>}<div className="mt-10 grid gap-5 md:grid-cols-3">{plans.map((plan) => <section key={plan.id} className={`relative rounded-3xl border bg-white p-7 shadow-sm ${plan.featured ? "border-[#087e8b] ring-2 ring-[#087e8b]/15" : "border-slate-200"}`}>{plan.featured && <span className="absolute -top-3 left-6 rounded-full bg-[#087e8b] px-3 py-1 text-xs font-bold text-white">Recommandé</span>}<h2 className="font-display text-2xl font-extrabold">{plan.name}</h2><p className="mt-3 text-3xl font-extrabold text-[#c91f3b]">{plan.price}</p><p className="mt-5 min-h-12 text-sm leading-6 text-slate-600">{plan.note}</p><button disabled={loading !== null} onClick={() => selectPlan(plan.id)} className="mt-7 w-full rounded-xl bg-[#071b36] py-3 text-sm font-bold text-white disabled:opacity-50">{loading === plan.id ? "Redirection…" : "Choisir ce plan"}</button></section>)}</div><p className="mt-8 text-center text-sm text-slate-500">Les entreprises disposent de deux publications gratuites à leur inscription. Un candidat peut publier son profil sans abonnement.</p></div></main>;
}
