"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

export default function AchatsPage() {
  const [orders, setOrders] = useState<any[]>([]);
  useEffect(() => { fetch("/api/auth/me").then((r) => r.json()).then((d) => { if (d.user) fetch(`/api/orders?userId=${encodeURIComponent(d.user.id)}`).then((r) => r.ok ? r.json() : { orders: [] }).then((data) => setOrders(data.orders || [])); }); }, []);
  const magazines = useMemo(() => orders.filter((order) => order.status === "paid").flatMap((order) => (order.items || []).filter((item: any) => item.type === "magazine" && ["numerique", "digital", "numérique"].includes(String(item.format || "").toLowerCase())).map((item: any) => ({ ...item, orderId: order.id, purchasedAt: order.paidAt || order.createdAt, currency: order.currency }))).filter((item: any, index: number, all: any[]) => all.findIndex((other) => other.magazineId === item.magazineId && other.language === item.language) === index), [orders]);
  return <div className="space-y-6"><div><p className="text-[11px] font-black uppercase tracking-[0.18em] text-[#D4AF37]">Bibliothèque personnelle</p><h1 className="mt-2 font-serif text-3xl font-black text-[#0A1931]">Mes magazines</h1><p className="mt-2 text-sm text-zinc-600">Les éditions numériques achetées et encore accessibles depuis votre compte.</p></div>{magazines.length === 0 ? <section className="rounded-[22px] border border-zinc-100 bg-white p-10 text-center shadow-sm"><h2 className="text-xl font-black text-[#0A1931]">Votre bibliothèque est vide</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-600">Vos magazines numériques apparaîtront ici après confirmation du paiement.</p><Link href="/kiosque" className="mt-6 inline-flex rounded-full bg-[#0A1931] px-5 py-3 text-sm font-bold text-white">Découvrir le kiosque</Link></section> : <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{magazines.map((item: any) => <article key={`${item.magazineId}-${item.language}`} className="overflow-hidden rounded-[22px] border border-zinc-100 bg-white shadow-sm"><div className="grid h-48 place-items-center bg-zinc-100"><span className="material-symbols-outlined text-5xl text-zinc-400">menu_book</span></div><div className="p-5"><p className="text-[11px] font-black uppercase tracking-wider text-[#D4AF37]">Magazine numérique</p><h2 className="mt-1 text-lg font-black text-[#0A1931]">{item.title || item.name || `Numéro ${item.numero || ""}`}</h2><p className="mt-2 text-xs text-zinc-500">Acheté le {new Date(item.purchasedAt).toLocaleDateString("fr-FR")} · Langue : {item.language || "FR"}</p><Link href={`/lecteur-document?magazineId=${encodeURIComponent(item.magazineId || "")}`} className="mt-4 inline-flex w-full items-center justify-center rounded-full bg-[#0A1931] px-4 py-3 text-sm font-bold text-white">Lire le magazine</Link></div></article>)}</section>}</div>;
}
