"use client";

import { useState } from "react";

const STEPS = ["Général", "Financement", "Objectif", "Description", "Médias", "Équipe", "Risques", "Récapitulatif"];
type FundingType = "donation" | "reward" | "equity" | "lending";
type WizardData = { nom: string; slogan: string; secteur: string; pays: string; ville: string; stade: string; typeFinancement: FundingType; devise: string; objectif: string; dureeJours: string; descriptionCourte: string; descriptionComplete: string; probleme: string; solution: string; image: string; video: string; role: string; risques: string; acceptCabinet: boolean; acceptTerms: boolean };
const initialData: WizardData = { nom: "", slogan: "", secteur: "", pays: "BJ", ville: "", stade: "Idée", typeFinancement: "donation", devise: "XOF", objectif: "", dureeJours: "30", descriptionCourte: "", descriptionComplete: "", probleme: "", solution: "", image: "", video: "", role: "", risques: "", acceptCabinet: false, acceptTerms: false };

export default function ProjectWizard() {
  const [step, setStep] = useState(0);
  const [data, setData] = useState<WizardData>(initialData);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const update = <K extends keyof WizardData>(key: K, value: WizardData[K]) => setData((current) => ({ ...current, [key]: value }));
  const canNext = () => {
    if (step === 0) return data.nom.trim().length >= 10 && Boolean(data.secteur) && Boolean(data.ville);
    if (step === 1) return Boolean(data.typeFinancement);
    if (step === 2) return Number(data.objectif) > 0 && Number(data.dureeJours) > 0 && Number(data.dureeJours) <= 90;
    if (step === 3) return data.descriptionCourte.trim().length >= 50 && data.descriptionComplete.trim().length >= 100 && data.probleme.trim() && data.solution.trim();
    if (step === 6) return data.risques.trim().length >= 30 && data.acceptTerms && (data.typeFinancement !== "equity" && data.typeFinancement !== "lending" || data.acceptCabinet);
    return true;
  };
  const saveDraft = async (submit = false) => {
    setSaving(true); setMessage("");
    try {
      const response = await fetch("/api/crowdfunding/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, nom: data.nom, secteur: data.secteur, description: data.descriptionCourte, montantRecherche: Number(data.objectif), pays: data.pays, dureeJours: Number(data.dureeJours), typesFinancement: [data.typeFinancement], statut: submit ? "pending_review" : "draft", images: data.image ? [data.image] : [], videos: data.video ? [data.video] : [] }) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Impossible d’enregistrer le projet");
      setMessage(submit ? "Projet soumis pour validation administrative." : "Brouillon enregistré. Il reste privé tant qu’il n’est pas soumis.");
      if (!submit) setData(initialData);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Erreur d’enregistrement"); } finally { setSaving(false); }
  };
  const inputClass = "w-full h-11 rounded-xl border border-[#e5bdbb] bg-white px-4 text-sm";
  return <section className="bg-white border border-[#e5bdbb] rounded-2xl p-5 md:p-7 mb-8">
    <div className="flex items-center justify-between gap-4"><div><p className="text-[11px] uppercase tracking-wider font-bold text-[#9e001f]">Nouveau projet</p><h2 className="text-xl font-black">Créer une campagne</h2></div><span className="text-xs text-[#5c403f]">Étape {step + 1} / {STEPS.length}</span></div>
    <div className="mt-5 flex gap-1 overflow-x-auto">{STEPS.map((label, index) => <button key={label} type="button" onClick={() => index <= step && setStep(index)} className={`whitespace-nowrap px-3 py-2 rounded-full text-[11px] font-bold ${index === step ? "bg-[#9e001f] text-white" : index < step ? "bg-[#ffdad8] text-[#9e001f]" : "bg-[#f6f3f2] text-[#5c403f]"}`}>{index + 1}. {label}</button>)}</div>
    <div className="mt-6 grid gap-4">
      {step === 0 && <><input className={inputClass} placeholder="Titre du projet (10 à 80 caractères)" value={data.nom} onChange={(e) => update("nom", e.target.value)} /><input className={inputClass} placeholder="Slogan / accroche" value={data.slogan} onChange={(e) => update("slogan", e.target.value)} /><div className="grid md:grid-cols-3 gap-3"><select className={inputClass} value={data.secteur} onChange={(e) => update("secteur", e.target.value)}><option value="">Secteur</option><option>Agri-business</option><option>Tech</option><option>Santé</option><option>Éducation</option><option>Commerce</option><option>Artisanat</option><option>Énergie</option><option>Services</option></select><select className={inputClass} value={data.pays} onChange={(e) => update("pays", e.target.value)}><option value="BJ">Bénin</option><option value="CI">Côte d’Ivoire</option><option value="SN">Sénégal</option><option value="CM">Cameroun</option><option value="NG">Nigeria</option><option value="GH">Ghana</option></select><input className={inputClass} placeholder="Ville / région" value={data.ville} onChange={(e) => update("ville", e.target.value)} /></div><select className={inputClass} value={data.stade} onChange={(e) => update("stade", e.target.value)}><option>Idée</option><option>Prototype</option><option>MVP lancé</option><option>En activité</option><option>Croissance / expansion</option></select></>}
      {step === 1 && <><p className="text-sm text-[#5c403f]">Choisissez le modèle de financement. Les paramètres détaillés seront complétés selon le type à l’étape suivante de construction.</p><div className="grid md:grid-cols-2 gap-3">{([["donation", "Don simple"], ["reward", "Don avec contrepartie"], ["equity", "Prise de participation"], ["lending", "Prêt"]] as const).map(([value, label]) => <button key={value} type="button" onClick={() => update("typeFinancement", value)} className={`text-left rounded-xl border p-4 ${data.typeFinancement === value ? "border-[#9e001f] bg-[#ffdad8]/30" : "border-[#e5bdbb]"}`}><strong>{label}</strong><span className="block text-xs text-[#5c403f] mt-1">Type extensible par l’administration.</span></button>)}</div></>}
      {step === 2 && <div className="grid md:grid-cols-3 gap-3"><select className={inputClass} value={data.devise} onChange={(e) => update("devise", e.target.value)}><option>XOF</option><option>XAF</option><option>NGN</option><option>GHS</option><option>USD</option><option>EUR</option></select><input className={inputClass} type="number" min="1" placeholder="Objectif financier" value={data.objectif} onChange={(e) => update("objectif", e.target.value)} /><input className={inputClass} type="number" min="1" max="90" placeholder="Durée en jours (max. 90)" value={data.dureeJours} onChange={(e) => update("dureeJours", e.target.value)} /></div>}
      {step === 3 && <><input className={inputClass} placeholder="Description courte (minimum 50 caractères)" value={data.descriptionCourte} onChange={(e) => update("descriptionCourte", e.target.value)} /><textarea className="w-full min-h-32 rounded-xl border border-[#e5bdbb] bg-white p-4 text-sm" placeholder="Description complète" value={data.descriptionComplete} onChange={(e) => update("descriptionComplete", e.target.value)} /><textarea className="w-full min-h-24 rounded-xl border border-[#e5bdbb] bg-white p-4 text-sm" placeholder="Quel problème le projet résout-il ?" value={data.probleme} onChange={(e) => update("probleme", e.target.value)} /><textarea className="w-full min-h-24 rounded-xl border border-[#e5bdbb] bg-white p-4 text-sm" placeholder="Quelle solution proposez-vous ?" value={data.solution} onChange={(e) => update("solution", e.target.value)} /></>}
      {step === 4 && <><input className={inputClass} placeholder="Lien de l’image de couverture" value={data.image} onChange={(e) => update("image", e.target.value)} /><input className={inputClass} placeholder="Lien vidéo YouTube / Vimeo (facultatif)" value={data.video} onChange={(e) => update("video", e.target.value)} /><p className="text-xs text-[#5c403f]">La première version accepte les liens vidéo ; l’upload vidéo sera ajouté ultérieurement.</p></>}
      {step === 5 && <><input className={inputClass} placeholder="Rôle du porteur dans le projet" value={data.role} onChange={(e) => update("role", e.target.value)} /><p className="text-xs text-[#5c403f]">Les membres de l’équipe et les documents justificatifs seront ajoutés dans la prochaine itération du wizard.</p></>}
      {step === 6 && <><textarea className="w-full min-h-28 rounded-xl border border-[#e5bdbb] bg-white p-4 text-sm" placeholder="Décrivez les risques du projet (minimum 30 caractères)" value={data.risques} onChange={(e) => update("risques", e.target.value)} /><label className="flex gap-3 items-start text-sm"><input type="checkbox" checked={data.acceptTerms} onChange={(e) => update("acceptTerms", e.target.checked)} /> J’ai lu et j’accepte les conditions générales et la charte du porteur.</label><label className="flex gap-3 items-start text-sm"><input type="checkbox" checked={data.acceptCabinet} onChange={(e) => update("acceptCabinet", e.target.checked)} /> J’accepte les règles d’accompagnement et de reporting applicables à mon type de financement.</label></>}
      {step === 7 && <div className="rounded-xl bg-[#f6f3f2] p-5 text-sm space-y-2"><p><strong>Titre :</strong> {data.nom || "—"}</p><p><strong>Type :</strong> {data.typeFinancement}</p><p><strong>Objectif :</strong> {data.objectif || "—"} {data.devise}</p><p><strong>Durée :</strong> {data.dureeJours} jours</p><p><strong>Statut après enregistrement :</strong> brouillon privé, puis soumission explicite pour validation.</p></div>}
    </div>
    {message && <p className="mt-4 rounded-xl bg-[#ffdad8]/40 p-3 text-sm text-[#9e001f]">{message}</p>}
    <div className="mt-6 flex flex-wrap justify-between gap-3"><button type="button" disabled={step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))} className="h-10 px-5 rounded-full border text-sm font-bold disabled:opacity-40">Précédent</button><div className="flex gap-2"><button type="button" disabled={saving} onClick={() => void saveDraft(false)} className="h-10 px-5 rounded-full border border-[#9e001f] text-[#9e001f] text-sm font-bold">Enregistrer brouillon</button>{step < STEPS.length - 1 ? <button type="button" disabled={!canNext()} onClick={() => setStep((current) => Math.min(STEPS.length - 1, current + 1))} className="h-10 px-5 rounded-full bg-[#9e001f] text-white text-sm font-bold disabled:opacity-40">Continuer</button> : <button type="button" disabled={!canNext() || saving} onClick={() => void saveDraft(true)} className="h-10 px-5 rounded-full bg-[#9e001f] text-white text-sm font-bold disabled:opacity-40">Soumettre pour validation</button>}</div></div>
  </section>;
}
