import { NextRequest, NextResponse } from "next/server";
import { getCurrentUserFromCookie } from "@/lib/auth";
import { createWabPost, readWabDB, writeWabDB } from "@/lib/wab-db";
import { WAB_BUSINESS_MONTHLY_PRICE } from "@/lib/wab-access";
import { hasWabBusinessVideoAccess } from "@/lib/wab-access-server";
import { createWabPostInSupabase, getWabProfileByUserId } from "@/lib/wab-supabase";

export async function GET(request: NextRequest) { const page = Math.max(1, Number(request.nextUrl.searchParams.get("page") ?? 1)); const limit = 8; const country = request.nextUrl.searchParams.get("country") ?? ""; const industry = request.nextUrl.searchParams.get("industry") ?? ""; const db = readWabDB(); const posts = db.posts.filter((post) => post.moderationStatus === "published").sort((a, b) => { const score = (post: typeof a) => { const campaign = db.boosts.find((boost) => boost.postId === post.id && boost.status === "active"); if (!campaign) return Date.parse(post.createdAt) / 1e12; const countryMatch = !campaign.targetCountries.length || campaign.targetCountries.some((target) => target.toLocaleLowerCase() === country.toLocaleLowerCase()); const industryMatch = !campaign.targetIndustries.length || campaign.targetIndustries.some((target) => target.toLocaleLowerCase() === industry.toLocaleLowerCase()); return 100 + (countryMatch ? 30 : 0) + (industryMatch ? 15 : 0) + Date.parse(post.createdAt) / 1e12; }; return score(b) - score(a); }); const start = (page - 1) * limit; return NextResponse.json({ posts: posts.slice(start, start + limit), pagination: { hasMore: start + limit < posts.length } }); }
export async function POST(request: NextRequest) { const user = await getCurrentUserFromCookie(); if (!user) return NextResponse.json({ error: "Connexion requise pour publier sur WAB." }, { status: 401 }); const body = await request.json(); if (typeof body.content !== "string" || body.content.trim().length < 2) return NextResponse.json({ error: "Votre publication doit contenir au moins deux caractères." }, { status: 400 }); const type = ["text", "opportunity", "document", "video"].includes(body.type) ? body.type : "text"; const media = Array.isArray(body.media) ? body.media.filter((item: unknown): item is { path: string; mimeType: string; name: string } => typeof item === "object" && item !== null && typeof (item as { path?: unknown }).path === "string" && typeof (item as { mimeType?: unknown }).mimeType === "string" && typeof (item as { name?: unknown }).name === "string").slice(0, 5) : []; const containsVideo = type === "video" || media.some((item: { path: string; mimeType: string; name: string }) => item.mimeType.toLocaleLowerCase().startsWith("video/")); if (containsVideo && !hasWabBusinessVideoAccess(user)) return NextResponse.json({ error: `La publication vidéo est réservée aux comptes Business avec un abonnement actif de ${WAB_BUSINESS_MONTHLY_PRICE.toLocaleString("fr-FR")} XOF par mois.`, upgradeUrl: "/wab" }, { status: 403 });   const tags = Array.isArray(body.tags) ? body.tags.filter((tag: unknown) => typeof tag === "string").slice(0, 8) : [];
  const supabaseProfile = await getWabProfileByUserId(user.id);
  if (supabaseProfile.configured) {
    if (!supabaseProfile.profile) return NextResponse.json({ error: "Votre profil WAB doit être configuré avant de publier." }, { status: 409 });
    const created = await createWabPostInSupabase(supabaseProfile.profile.id, { content: body.content.trim().slice(0, 10000), type, media, tags });
    if (!created.post) return NextResponse.json({ error: "Impossible d’enregistrer votre publication." }, { status: 500 });
    const row = created.post;
    const profile = row.wab_profiles;
    return NextResponse.json({ post: { id: row.id, author: profile?.fullName || `${user.prenom} ${user.nom}`, authorAvatarUrl: profile?.avatar_url || undefined, authorUserId: user.id, headline: profile?.headline || user.company || "Professionnel Envol Africa", location: [profile?.city, profile?.country_code].filter(Boolean).join(", ") || user.country || "Afrique", content: row.content, type: row.content_type, media: row.media ?? [], tags, views: row.views_count ?? 0, watchSeconds: row.watch_seconds ?? 0, likes: row.likes_count ?? 0, comments: row.comments_count ?? 0, shares: row.shares_count ?? 0, isBoosted: row.is_boosted ?? false, createdAt: row.created_at, moderationStatus: row.moderation_status } }, { status: 201 });
  }
  const post = createWabPost({ author: `${user.prenom} ${user.nom}`, authorAvatarUrl: typeof (user as { avatarUrl?: unknown }).avatarUrl === "string" ? (user as unknown as { avatarUrl: string }).avatarUrl : undefined, authorUserId: user.id, headline: user.company || "Professionnel Envol Africa", location: user.country || "Afrique", content: body.content.trim().slice(0, 10000), type, media, tags }); const db = readWabDB(); const stored = db.posts.find((item) => item.id === post.id); if (media.length && stored) { post.moderationStatus = "pending_review"; stored.moderationStatus = "pending_review"; } if (!media.length) { const profile = db.profiles.find((item) => item.userId === user.id); if (profile) db.connections.filter((connection) => connection.profileId === profile.id).forEach((connection) => db.notifications.unshift({ id: crypto.randomUUID(), userId: connection.followerUserId, type: "followed_profile_post", title: `${user.prenom} ${user.nom} a publié sur WAB`, body: post.content.slice(0, 150), href: "/wab", createdAt: new Date().toISOString() })); } writeWabDB(db); return NextResponse.json({ post }, { status: 201 }); }
