"use client";

import { useEffect, useState } from "react";

type Group = { id: string; name: string; description?: string; logoUrl?: string; privacy: "community" | "private"; memberCount: number };
type Membership = { role: string; status: string } | null;

export default function WabGroupPage({ params }: { params: Promise<{ id: string }> }) {
  const [group, setGroup] = useState<Group | null>(null);
  const [membership, setMembership] = useState<Membership>(null);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  useEffect(() => { params.then(({ id }) => fetch(`/api/wab/groups/${id}`).then((response) => response.json()).then((data) => { if (!data.group) throw new Error(data.error); setGroup(data.group); setMembership(data.membership); }).catch((error) => setMessage(error instanceof Error ? error.message : "Groupe indisponible."))); }, [params]);
  async function join() { if (!group) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/wab/groups/${group.id}/join`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMembership(data.membership); setGroup((current) => current ? { ...current, memberCount: data.membership?.status === "active" ? current.memberCount + 1 : current.memberCount } : current); setMessage(data.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Impossible de rejoindre le groupe."); } finally { setBusy(false); } }
  if (!group) return <main className="min-h-screen bg-[#e9f7f5] px-5 py-12"><div className="mx-auto max-w-3xl rounded-3xl bg-white p-8 text-center">{message || "Chargement du groupe…"}</div></main>;
  return <main className="min-h-screen bg-[#e9f7f5] px-5 py-10"><div className="mx-auto max-w-3xl"><a href="/wab" className="text-sm font-bold text-[#006874]">← Retour au fil WAB</a><section className="mt-6 rounded-3xl border border-[#d1e9e6] bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-center gap-4"><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-2xl bg-[#eefcfa] text-[#006874]">{group.logoUrl ? <img src={group.logoUrl} alt="" className="h-full w-full object-contain p-2" /> : <span className="material-symbols-outlined text-4xl">groups</span>}</div><div><p className="text-xs font-bold uppercase tracking-widest text-[#006874]">Groupe WAB</p><h1 className="mt-1 font-display text-3xl font-extrabold text-[#082843]">{group.name}</h1><p className="mt-1 text-sm text-[#43474d]">{group.privacy === "private" ? "Groupe privé" : "Groupe communautaire"} · {group.memberCount} membre{group.memberCount > 1 ? "s" : ""}</p></div></div><p className="mt-6 leading-7 text-[#111e1d]">{group.description || "Un espace de discussion et de publication au sein du réseau WAB."}</p><div className="mt-6 flex flex-wrap items-center gap-3">{membership?.status === "active" ? <span className="rounded-full bg-[#e9f7f5] px-4 py-2 text-sm font-bold text-[#006874]">Vous êtes membre · vous pouvez publier</span> : membership?.status === "pending" ? <span className="rounded-full bg-[#fff3dc] px-4 py-2 text-sm font-bold text-[#875600]">Demande en attente</span> : <button type="button" onClick={join} disabled={busy} className="rounded-xl bg-[#006874] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy ? "Envoi…" : group.privacy === "private" ? "Demander à rejoindre" : "Rejoindre le groupe"}</button>}<a href={`/wab#publier`} className="rounded-xl border border-[#d1e9e6] px-5 py-3 text-sm font-bold text-[#006874]">Créer une publication</a></div>{message && <p className="mt-4 rounded-xl bg-[#eefcfa] p-3 text-sm font-semibold text-[#006874]">{message}</p>}</section></div></main>;
}
