import { NextRequest, NextResponse } from "next/server";
import { getCurrentUserFromCookie } from "@/lib/auth";
import { EMPLOYER_PLANS, JOB_SEEKER_PLANS, readJobsDB, writeJobsDB } from "@/lib/jobs-db";
import { verifyMonerooPayment } from "@/lib/moneroo";
import { activateJobsSubscription, getJobsSubscriptionById } from "@/lib/jobs-payments-supabase";

export async function POST(_request: NextRequest, { params }: { params: Promise<{ subscriptionId: string }> }) {
 const user = await getCurrentUserFromCookie(); if (!user) return NextResponse.json({ error: "Connexion requise." }, { status: 401 }); const { subscriptionId } = await params;
 const persisted = await getJobsSubscriptionById(user.id, subscriptionId);
 if (persisted.configured) { const subscription = persisted.subscription; if (!subscription) return NextResponse.json({ error: "Abonnement introuvable." }, { status: 404 }); if (subscription.status === "active") return NextResponse.json({ active: true }); if (!subscription.provider_payment_id) return NextResponse.json({ error: "Paiement introuvable." }, { status: 400 }); const result = await verifyMonerooPayment(subscription.provider_payment_id); if (!["success", "paid", "completed"].includes(String(result.status))) return NextResponse.json({ active: false, status: "pending" }); const activated = await activateJobsSubscription(user.id, subscriptionId); return NextResponse.json({ active: activated.active }); }
 const database = readJobsDB(); const subscription = database.subscriptions.find((item) => item.id === subscriptionId && item.userId === user.id); if (!subscription) return NextResponse.json({ error: "Abonnement introuvable." }, { status: 404 }); if (subscription.status === "active") return NextResponse.json({ active: true }); if (!subscription.paymentId) return NextResponse.json({ error: "Paiement introuvable." }, { status: 400 }); const result = await verifyMonerooPayment(subscription.paymentId); if (!["success", "paid", "completed"].includes(String(result.status))) return NextResponse.json({ active: false, status: "pending" }); const plan = (subscription.audience === "candidate" ? JOB_SEEKER_PLANS : EMPLOYER_PLANS).find((item) => item.id === subscription.planId); const now = new Date(); subscription.status = "active"; subscription.startsAt = now.toISOString(); if (plan && "durationHours" in plan) subscription.endsAt = new Date(now.getTime() + plan.durationHours * 3600000).toISOString(); else if (plan && "durationDays" in plan && plan.durationDays > 0) subscription.endsAt = new Date(now.getTime() + plan.durationDays * 86400000).toISOString(); writeJobsDB(database); return NextResponse.json({ active: true });
}
