"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Tab = "notifications" | "messages" | "favorites";
type InboxMessage = { id: string; platform: string; body: string; subject?: string | null; href?: string | null; readAt?: string | null; createdAt: string; senderId?: string | null; senderName?: string; senderAvatar?: string };
type InboxNotification = { id: string; title: string; body: string; link?: string | null; readAt?: string | null; createdAt: string };

const labels: Record<Tab, string> = { notifications: "Notifications", messages: "Messages", favorites: "Favoris" };

export default function InboxToolbox({ open, tab, onClose }: { open: boolean; tab: Tab; onClose: () => void }) {
  const [messages, setMessages] = useState<InboxMessage[]>([]);
  const [notifications, setNotifications] = useState<InboxNotification[]>([]);
  const [loading, setLoading] = useState(false);
  useEffect(() => { if (!open) return; setLoading(true); Promise.all([fetch("/api/messages", { cache: "no-store" }).then((r) => r.ok ? r.json() : { messages: [] }), fetch("/api/notifications", { cache: "no-store" }).then((r) => r.ok ? r.json() : { notifications: [] })]).then(([messageData, notificationData]) => { setMessages(messageData.messages || []); setNotifications(notificationData.notifications || []); }).finally(() => setLoading(false)); }, [open]);
  if (!open) return null;
  return <div className="fixed inset-x-3 top-[64px] z-[95] max-h-[75vh] overflow-y-auto rounded-2xl border border-[#e5bdbb] bg-white p-4 text-[#242020] shadow-2xl dark:bg-[#241d1f] dark:text-white md:inset-x-auto md:right-6 md:w-[390px] lg:top-[84px]" role="dialog" aria-label={labels[tab]}><div className="flex items-center justify-between border-b border-[#f0dedd] pb-3"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-[#9e001f]">Écosystème Envol Africa</p><h2 className="font-display text-lg font-black">{labels[tab]}</h2></div><button type="button" onClick={onClose} aria-label="Fermer" className="grid h-9 w-9 place-items-center rounded-full bg-[#f6f3f2] text-[#9e001f]"><span className="material-symbols-outlined">close</span></button></div><div className="mt-3 flex gap-2">{(Object.keys(labels) as Tab[]).map((item) => <Link key={item} href={item === "notifications" ? "/notifications" : item === "messages" ? "/messages" : "/compte/favoris"} onClick={onClose} className={`rounded-full px-3 py-1.5 text-[11px] font-black ${item === tab ? "bg-[#9e001f] text-white" : "bg-[#f6f3f2] text-[#725f4d]"}`}>{labels[item]}</Link>)}</div>{loading ? <p className="py-8 text-center text-sm text-[#806c58]">Chargement…</p> : tab === "messages" ? <div className="mt-3 divide-y divide-[#f0dedd]">{messages.slice(0, 8).map((item) => <Link key={item.id} href={item.href || "/messages"} onClick={onClose} className="flex gap-3 py-3 transition hover:bg-[#fff8f6]"><span className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-full bg-[#f6f3f2] text-[#9e001f]">{item.senderAvatar ? <img src={item.senderAvatar} alt="" className="h-full w-full object-cover" /> : <span className="material-symbols-outlined">person</span>}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs font-black">{item.senderName || item.subject || "Nouveau message"}</strong><span className="mt-1 block truncate text-xs text-[#806c58]">{item.body}</span></span></Link>)}{messages.length === 0 && <p className="py-8 text-center text-sm text-[#806c58]">Aucun message reçu.</p>}</div> : tab === "notifications" ? <div className="mt-3 divide-y divide-[#f0dedd]">{notifications.slice(0, 8).map((item) => <Link key={item.id} href={item.link || "/notifications"} onClick={onClose} className="flex gap-3 py-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#f6f3f2] text-[#9e001f]"><span className="material-symbols-outlined">notifications</span></span><span className="min-w-0 flex-1"><strong className="block truncate text-xs font-black">{item.title}</strong><span className="mt-1 block truncate text-xs text-[#806c58]">{item.body}</span></span></Link>)}{notifications.length === 0 && <p className="py-8 text-center text-sm text-[#806c58]">Aucune notification.</p>}</div> : <div className="mt-3 rounded-xl bg-[#fff8f6] p-4 text-sm text-[#725f4d]">Retrouvez vos articles et contenus enregistrés dans votre espace Favoris.</div>}</div>;
}
export type { Tab as InboxToolboxTab };

