"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Order = { id: string; product_id: string; total_xof: number; payment_mode: string; status: string; created_at: string };
type Download = { id: string; order_id: string; download_count: number; max_downloads: number; expires_at: string; downloadUrl: string; marketplace_products?: { title?: string; product_type?: string; digital_access_instructions?: string | null } | null };

export default function MarketplaceOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [downloads, setDownloads] = useState<Download[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/marketplace/orders", { cache: "no-store" }), fetch("/api/marketplace/downloads", { cache: "no-store" })]).then(async ([ordersResponse, downloadsResponse]) => { if (ordersResponse.status === 401) { window.location.assign("/auth/login?next=/marketplace/commandes"); return; } const ordersData = await ordersResponse.json(); const downloadsData = await downloadsResponse.json(); if (!ordersResponse.ok) throw new Error(ordersData.error || "Impossible de charger les commandes."); setOrders(ordersData.orders || []); if (downloadsResponse.ok) setDownloads(downloadsData.downloads || []); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Impossible de charger vos commandes.")).finally(() => setLoading(false)); }, []);
  return <main className="min-h-screen bg-[#fcf9f8] px-5 py-12 text-[#2a211a] md:px-10 lg:px-16"><div className="mx-auto max-w-5xl"><Link href="/marketplace" className="text-xs font-bold text-[#9e001f]">← Retour au Marketplace</Link><h1 className="mt-8 font-display text-4xl font-black">Mes commandes Marketplace</h1><p className="mt-3 text-sm leading-6 text-[#725f4d]">Retrouvez vos commandes, vos paiements et les accès numériques obtenus après confirmation.</p>{loading && <p className="mt-8 rounded-2xl bg-white p-6 text-sm text-[#806c58]">Chargement de votre espace…</p>}{error && <p className="mt-8 rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-800">{error}</p>}{!loading && !error && <><section className="mt-8 rounded-[24px] border border-[#eadfce] bg-white p-6"><h2 className="font-display text-xl font-black">Accès numériques</h2><p className="mt-2 text-sm text-[#725f4d]">Les fichiers et liens sont disponibles uniquement après paiement confirmé.</p>{downloads.length ? <div className="mt-5 space-y-3">{downloads.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#eadfce] bg-[#fffaf3] p-4"><div><strong className="block text-sm">{item.marketplace_products?.title || "Produit numérique"}</strong><span className="mt-1 block text-xs text-[#806c58]">Téléchargements : {item.download_count}/{item.max_downloads} · expire le {new Date(item.expires_at).toLocaleDateString("fr-FR")}</span>{item.marketplace_products?.digital_access_instructions && <span className="mt-2 block text-xs text-[#725f4d]">{item.marketplace_products.digital_access_instructions}</span>}</div><a href={item.downloadUrl} className="rounded-full bg-[#9e001f] px-4 py-2 text-xs font-black text-white">Ouvrir / télécharger</a></article>)}</div> : <p className="mt-5 rounded-xl bg-[#fff8f6] p-4 text-sm text-[#806c58]">Aucun accès numérique confirmé pour le moment.</p>}</section><section className="mt-6 rounded-[24px] border border-[#eadfce] bg-white p-6"><h2 className="font-display text-xl font-black">Historique des commandes</h2>{orders.length ? <div className="mt-5 space-y-3">{orders.map((order) => <article key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#eadfce] p-4"><div><strong className="block text-sm">Commande {order.id.slice(0, 8)}</strong><span className="mt-1 block text-xs text-[#806c58]">{new Date(order.created_at).toLocaleDateString("fr-FR")} · {order.payment_mode === "installment" ? "Paiement échelonné" : "Paiement comptant"}</span></div><div className="text-right"><strong className="block text-sm text-[#9e001f]">{new Intl.NumberFormat("fr-FR").format(order.total_xof)} XOF</strong><span className="text-xs font-bold text-[#087e8b]">{order.status}</span></div></article>)}</div> : <p className="mt-5 rounded-xl bg-[#fff8f6] p-4 text-sm text-[#806c58]">Aucune commande enregistrée.</p>}</section></>}</div></main>;
}
