// Style Envol Africa : politique de confidentialité lisible, directe et accessible aux utilisateurs comme aux crawlers.
import Link from "next/link";

export const metadata = {
  title: "Politique de confidentialité | Envol Africa",
  description: "Politique de confidentialité et de protection des données d’Envol Africa.",
  robots: { index: true, follow: true },
};

const updated = "24 août 2026";

export default function ConfidentialitePage() {
  return (
    <main className="mx-auto w-full max-w-4xl px-5 py-14 md:px-10 md:py-24">
      <Link href="/" className="font-sans text-xs font-bold text-[#9e001f]">← Retour au Magazine</Link>
      <p className="mt-10 font-sans text-[10px] font-black uppercase tracking-[0.18em] text-[#9e001f]">Document officiel · Mise à jour : {updated}</p>
      <h1 className="mt-3 font-serif text-4xl leading-tight text-[#292323] md:text-6xl">Politique de confidentialité</h1>
      <p className="mt-6 max-w-3xl font-sans text-sm leading-7 text-[#635655]">Cette politique explique quelles données Envol Africa Groupe collecte, pourquoi elles sont utilisées, avec qui elles peuvent être partagées et comment demander leur accès, leur rectification ou leur suppression.</p>

      <article className="mt-12 space-y-9 font-sans text-sm leading-7 text-[#443a39]">
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">1. Données collectées</h2><p className="mt-2">Selon le service utilisé, nous pouvons traiter votre nom, prénom, adresse e-mail, numéro de téléphone, pays, langue et devise préférées, photo de profil, informations de compte, contenus publiés, messages, commentaires, réactions, candidatures, commandes, abonnements et historique des opérations. Nous pouvons également recevoir une confirmation limitée d’un fournisseur OAuth lorsque vous choisissez Google, Facebook ou TikTok.</p><p className="mt-2">Le navigateur et le serveur peuvent transmettre des données techniques telles que l’adresse IP, le type d’appareil, le navigateur, les journaux de sécurité, les pages consultées et les événements nécessaires au fonctionnement. Les données complètes de carte bancaire sont traitées par le prestataire de paiement et ne sont pas stockées par l’application.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">2. Finalités</h2><p className="mt-2">Nous utilisons ces informations pour créer et sécuriser les comptes, fournir les services demandés, gérer les abonnements, commandes, candidatures et paiements, publier les contenus choisis par l’utilisateur, personnaliser la langue, la devise et l’expérience, prévenir la fraude, répondre aux demandes, envoyer les notifications demandées et mesurer l’usage lorsque le consentement est requis.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">3. Bases et choix de l’utilisateur</h2><p className="mt-2">Le traitement peut être nécessaire à l’exécution d’un service demandé, au respect d’une obligation légale, à la sécurité et aux intérêts légitimes d’Envol Africa, ou reposer sur votre consentement. Lorsque le consentement est requis, vous pouvez le retirer à tout moment sans affecter la licéité du traitement antérieur. Les préférences de cookies sont détaillées dans la <Link href="/cookies" className="font-bold text-[#9e001f] underline">Politique relative aux cookies</Link>.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">4. Partage et prestataires</h2><p className="mt-2">Les données peuvent être accessibles aux prestataires qui hébergent, sécurisent, authentifient, analysent, notifient ou traitent les paiements pour notre compte, uniquement dans la mesure nécessaire au service. Les fournisseurs OAuth et les plateformes sociales appliquent également leurs propres politiques. Nous ne vendons pas les données personnelles. Nous pouvons les communiquer lorsque la loi l’exige, pour protéger les utilisateurs ou pour prévenir une fraude.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">5. Contenus publics</h2><p className="mt-2">Les publications, profils, commentaires, annonces et autres contenus que vous choisissez de rendre publics peuvent être visibles par d’autres visiteurs et indexés selon les réglages du service. Ne publiez pas de données sensibles concernant vous-même ou une autre personne. Vous pouvez demander la modification ou le retrait d’un contenu selon les fonctionnalités disponibles et les règles applicables.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">6. Conservation et sécurité</h2><p className="mt-2">Nous conservons les données pendant la durée nécessaire aux finalités décrites, puis les supprimons, anonymisons ou archivons lorsque la loi ou la preuve d’une transaction l’exige. Nous appliquons des mesures raisonnables de contrôle d’accès, chiffrement en transit, journalisation et limitation des privilèges. Aucun système ne garantit un risque nul ; signalez rapidement tout incident via la page <Link href="/service" className="font-bold text-[#9e001f] underline">Contact</Link>.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">7. Vos droits et suppression du compte</h2><p className="mt-2">Selon votre pays, vous pouvez demander l’accès, la rectification, la portabilité, la limitation, l’opposition ou la suppression de vos données. Pour exercer un droit, utilisez le formulaire de <Link href="/service" className="font-bold text-[#9e001f] underline">Contact</Link> et indiquez l’adresse e-mail du compte, le droit exercé et les éléments permettant de traiter la demande. Nous pouvons demander une vérification raisonnable de votre identité. La suppression du compte peut être différée pour les obligations légales, la sécurité, la prévention de la fraude ou la résolution d’un litige.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">8. Enfants</h2><p className="mt-2">Les services ne sont pas destinés aux personnes qui ne peuvent pas légalement consentir au traitement de leurs données dans leur pays. Si vous pensez qu’un mineur a fourni des données sans autorisation appropriée, contactez-nous afin que nous puissions examiner la situation.</p></section>
        <section><h2 className="font-display text-xl font-extrabold text-[#292323]">9. Transferts et changements</h2><p className="mt-2">Certains prestataires peuvent traiter des données depuis un autre pays. Nous mettons en place les garanties appropriées lorsque la réglementation l’exige. Cette politique peut être mise à jour ; sa date de version est affichée en haut de page et les changements importants seront signalés de manière appropriée.</p></section>
      </article>

      <div className="mt-12 flex flex-wrap gap-4 border-t border-[#e5d9d7] pt-6 font-sans text-xs font-bold text-[#9e001f]"><Link href="/conditions" className="underline">Conditions d’utilisation</Link><Link href="/cookies" className="underline">Politique cookies</Link><Link href="/service" className="underline">Demander mes droits ou supprimer mon compte</Link></div>
    </main>
  );
}
