import { NextRequest, NextResponse } from "next/server";
import { getCurrentUserFromCookie } from "@/lib/auth";
import { readJobsDB, writeJobsDB } from "@/lib/jobs-db";

async function canManageJobs() { const user = await getCurrentUserFromCookie(); return user && ["admin", "administrateur", "gerant"].includes(user.role) ? user : null; }

export async function GET() { const user = await canManageJobs(); if (!user) return NextResponse.json({ error: "Accès refusé." }, { status: 403 }); const db = readJobsDB(); return NextResponse.json({ offers: db.offers, candidates: db.candidates, subscriptions: db.subscriptions, boosts: db.boosts, applications: db.applications, metrics: { offers: db.offers.length, candidates: db.candidates.length, applications: db.applications.length, paidUnlocks: db.unlocks.filter((item) => item.status === "paid").length, activeBoosts: db.boosts.filter((item) => item.status === "active").length } }); }

export async function PATCH(request: NextRequest) { const user = await canManageJobs(); if (!user) return NextResponse.json({ error: "Accès refusé." }, { status: 403 }); const { targetType, targetId, status } = await request.json(); const validOffer = ["draft", "pending_review", "published", "closed", "rejected", "archived"]; const validCandidate = ["draft", "pending_review", "published", "hidden", "archived"]; const db = readJobsDB(); if (targetType === "offer" && validOffer.includes(status)) { const offer = db.offers.find((item) => item.id === targetId); if (!offer) return NextResponse.json({ error: "Offre introuvable." }, { status: 404 }); offer.status = status; writeJobsDB(db); return NextResponse.json({ offer }); } if (targetType === "candidate" && validCandidate.includes(status)) { const candidate = db.candidates.find((item) => item.id === targetId); if (!candidate) return NextResponse.json({ error: "Candidat introuvable." }, { status: 404 }); candidate.status = status; writeJobsDB(db); return NextResponse.json({ candidate }); } return NextResponse.json({ error: "Action invalide." }, { status: 400 }); }
