"use client";

import { useEffect, useMemo, useState } from "react";

type MediaType = "story" | "reel";
type Reaction = "love" | "like" | "laugh" | "sad" | "cry" | "wow";
type Comment = { id: string; author: string; content: string; createdAt: string };
const reactions: Array<{ key: Reaction; icon: string; label: string }> = [{ key: "love", icon: "♥", label: "Amour" }, { key: "like", icon: "✓", label: "Validation" }, { key: "laugh", icon: "笑", label: "Rire" }, { key: "sad", icon: "☹", label: "Tristesse" }, { key: "cry", icon: "涙", label: "Pleurs" }, { key: "wow", icon: "!", label: "Surprise" }];

export default function MediaInteractions({ mediaType, mediaId, caption, onCommentCountChange }: { mediaType: MediaType; mediaId: string; caption?: string; onCommentCountChange?: (count: number) => void }) {
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [myReaction, setMyReaction] = useState<Reaction | null>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [content, setContent] = useState("");
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const total = useMemo(() => Object.values(counts).reduce((sum, value) => sum + Number(value || 0), 0), [counts]);
  useEffect(() => { fetch(`/api/wab/media-interactions?mediaType=${mediaType}&mediaId=${encodeURIComponent(mediaId)}`).then((response) => response.json()).then((data) => { setCounts(data.counts ?? {}); setMyReaction(data.myReaction ?? null); setComments(data.comments ?? []); onCommentCountChange?.((data.comments ?? []).length); }).catch(() => setNotice("Interactions indisponibles pour le moment.")); }, [mediaId, mediaType, onCommentCountChange]);
  async function react(reaction: Reaction) { setNotice(""); const response = await fetch("/api/wab/media-interactions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mediaType, mediaId, reaction }) }); const data = await response.json().catch(() => ({})); if (response.status === 401) { window.location.assign(`/auth/login?next=${encodeURIComponent("/wab")}`); return; } if (!response.ok) { setNotice(data.error || "Connexion requise pour réagir."); return; } setMyReaction(data.reaction ?? null); setCounts((current) => ({ ...current, [reaction]: Math.max(0, Number(current[reaction] ?? 0) + (data.reaction ? 1 : -1)) })); }
  async function comment(event: React.FormEvent) { event.preventDefault(); if (!content.trim() || busy) return; setBusy(true); setNotice(""); const response = await fetch("/api/wab/media-interactions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mediaType, mediaId, content }) }); const data = await response.json().catch(() => ({})); if (response.status === 401) { window.location.assign(`/auth/login?next=${encodeURIComponent("/wab")}`); return; } if (!response.ok) setNotice(data.error || "Commentaire impossible."); else { setComments((current) => [...current, data.comment]); setContent(""); onCommentCountChange?.(comments.length + 1); } setBusy(false); }
  return <div className="absolute inset-x-0 bottom-0 max-h-[58%] overflow-y-auto bg-gradient-to-t from-black via-black/90 to-black/20 px-4 pb-4 pt-16 text-white">{caption && <p className="mb-3 text-sm font-semibold text-white">{caption}</p>}<div className="flex items-center justify-between gap-3"><span className="text-xs font-bold">{total} réaction{total > 1 ? "s" : ""} · {comments.length} commentaire{comments.length > 1 ? "s" : ""}</span><div className="flex gap-1">{reactions.map((item) => <button key={item.key} type="button" title={item.label} aria-label={item.label} aria-pressed={myReaction === item.key} onClick={() => void react(item.key)} className={`grid h-8 w-8 place-items-center rounded-full text-sm transition hover:bg-white/20 ${myReaction === item.key ? "bg-[#8ee0c0] text-[#082843]" : "bg-white/10 text-white"}`}>{item.icon}</button>)}</div></div><div className="mt-3 space-y-2">{comments.slice(-4).map((item) => <div key={item.id} className="rounded-xl bg-white/10 px-3 py-2 text-xs"><strong>{item.author}</strong><p className="mt-1 text-white/90">{item.content}</p></div>)}</div><form onSubmit={comment} className="mt-3 flex gap-2"><input value={content} onChange={(event) => setContent(event.target.value)} placeholder="Écrire un commentaire…" className="min-w-0 flex-1 rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-xs text-white outline-none placeholder:text-white/60" /><button type="submit" disabled={busy || !content.trim()} className="rounded-xl bg-[#8ee0c0] px-3 py-2 text-xs font-bold text-[#082843] disabled:opacity-50">{busy ? "…" : "Envoyer"}</button></form>{notice && <p className="mt-2 text-[11px] text-[#ffdca8]">{notice}</p>}</div>;
}
