"use client";
import { useEffect, useState } from "react";
import TrackedVideo from "./TrackedVideo";
import Link from "next/link";
import { internalDocumentHref } from "@/lib/internal-browser";
type Media = { path: string; mimeType: string; name: string };
type ResolvedMedia = { url: string; mimeType: string; name: string };
function fileKind(mimeType: string, name: string) { const lowerName = name.toLowerCase(); if (mimeType === "application/pdf" || lowerName.endsWith(".pdf")) return { icon: "picture_as_pdf", label: "PDF", color: "text-[#c62828]" }; if (mimeType.includes("word") || /\.(doc|docx)$/.test(lowerName)) return { icon: "description", label: "Word", color: "text-[#185abd]" }; if (mimeType.includes("excel") || /\.(xls|xlsx|csv)$/.test(lowerName)) return { icon: "table_chart", label: "Excel", color: "text-[#188038]" }; if (mimeType.includes("powerpoint") || /\.(ppt|pptx)$/.test(lowerName)) return { icon: "slideshow", label: "PowerPoint", color: "text-[#d24726]" }; if (mimeType.startsWith("image/")) return { icon: "image", label: "Image", color: "text-[#087e8b]" }; if (mimeType.startsWith("video/")) return { icon: "videocam", label: "Vidéo", color: "text-[#7b1fa2]" }; if (mimeType.startsWith("audio/")) return { icon: "audio_file", label: "Audio", color: "text-[#a36300]" }; return { icon: "description", label: "Fichier", color: "text-[#006874]" }; }
export default function PostMedia({ postId, media }: { postId: string; media: Media[] }) {
  const [urls, setUrls] = useState<ResolvedMedia[]>([]);
  useEffect(() => { Promise.all(media.map((_, index) => fetch(`/api/wab/media?postId=${postId}&index=${index}`).then((response) => response.ok ? response.json() : null))).then((values) => setUrls(values.filter(Boolean))); }, [media, postId]);
  if (!urls.length) return null;
  const first = urls[0];
  const firstIsDocument = first.mimeType === "application/pdf" || first.mimeType === "application/msword" || first.mimeType.includes("wordprocessingml") || first.mimeType.includes("spreadsheetml") || first.mimeType.includes("presentationml") || first.mimeType.includes("ms-excel") || first.mimeType.includes("ms-powerpoint") || first.mimeType === "text/csv" || /\.(pdf|doc|docx|xls|xlsx|csv|ppt|pptx)$/i.test(first.name);
  const preview = first.mimeType.startsWith("image/") ? <img src={first.url} alt={first.name} className="max-h-[520px] w-full rounded-xl object-cover" /> : first.mimeType.startsWith("video/") ? <TrackedVideo postId={postId} src={first.url} name={first.name} /> : first.mimeType.startsWith("audio/") ? <audio controls src={first.url} className="w-full" /> : firstIsDocument ? (() => { const internalHref = internalDocumentHref(first.url, first.name, first.mimeType); const documentHref = internalHref || first.url; return <a href={documentHref} target={internalHref ? undefined : "_blank"} rel={internalHref ? undefined : "noreferrer"} className="group block overflow-hidden rounded-xl border border-[#d1e9e6] bg-[#f7fcfb]" title={`Ouvrir ${first.name}`}><img src={`/api/wab/media/preview?postId=${encodeURIComponent(postId)}&index=0`} alt={`Aperçu de la première page de ${first.name}`} className="max-h-[520px] min-h-[180px] w-full bg-white object-contain transition group-hover:opacity-90" onError={(event) => { event.currentTarget.style.display = "none"; }} /><span className="flex items-center justify-between gap-3 px-4 py-3 text-xs font-bold text-[#087e8b]"><span className="truncate">{first.name}</span><span className="material-symbols-outlined text-[18px]">download</span></span></a>; })() : (() => { const internalHref = internalDocumentHref(first.url, first.name, first.mimeType); return internalHref ? <Link href={internalHref} className="block rounded-xl bg-[#e9f7f5] p-4 text-sm font-bold text-[#087e8b]">Lire le document dans EAM : {first.name} ↗</Link> : <a href={first.url} target="_blank" rel="noreferrer" className="block rounded-xl bg-[#e9f7f5] p-4 text-sm font-bold text-[#087e8b]">Ouvrir le document : {first.name} ↗</a>; })();
  return <div className="mt-5 space-y-2"><div>{preview}</div><div className="flex flex-wrap items-center gap-2 rounded-xl bg-[#f5fbfa] px-3 py-2 text-xs font-bold text-[#006874]" aria-label={`${media.length} pièce${media.length > 1 ? "s" : ""} jointe${media.length > 1 ? "s" : ""}`}><span className="font-display text-sm font-black text-[#2a211a]">{media.length}</span><span className="material-symbols-outlined text-[18px]" aria-hidden="true">attach_file</span>{media.map((item, index) => { const kind = fileKind(item.mimeType, item.name); return <span key={`${item.path}-${index}`} className={`inline-flex items-center gap-1 rounded-full bg-white px-2 py-1 ${kind.color}`} title={item.name}><span className="material-symbols-outlined text-[15px]">{kind.icon}</span><span>{kind.label}</span></span>; })}</div></div>;
}
