"use client";
import { useEffect, useState } from "react";

function Badge({ count }: { count: number }) { return count > 0 ? <span className="absolute -right-1 -top-1 grid min-h-4 min-w-4 place-items-center rounded-full bg-[#c1121f] px-1 text-[9px] font-extrabold leading-none text-white">{count > 99 ? "99+" : count}</span> : null; }

export default function WabSocialHeader({ avatar }: { avatar?: string }) {
  const [messages, setMessages] = useState(0);
  const [notifications, setNotifications] = useState(0);
  useEffect(() => { const load = () => { fetch("/api/wab/messages").then((response) => response.json()).then((data) => setMessages(Number(data.unreadCount || 0))).catch(() => undefined); fetch("/api/wab/notifications").then((response) => response.json()).then((data) => setNotifications(Number(data.unreadCount || 0))).catch(() => undefined); }; load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, []);
  return <header className="sticky top-0 z-40 border-b border-[#d1e9e6] bg-[#eefcfa]/95 shadow-sm backdrop-blur"><div className="mx-auto flex h-14 max-w-[1200px] items-center justify-between px-4 md:px-10"><a href="/wab" className="font-display text-2xl font-extrabold tracking-tight text-[#001325]">WAB</a><nav className="flex items-center gap-2" aria-label="Actions sociales"><a href="/wab/messages" className="relative grid h-10 w-10 place-items-center rounded-full text-[#006874] hover:bg-[#d7e5e3]" aria-label={`Messages${messages ? `, ${messages} non lus` : ""}`}><span className="material-symbols-outlined">mail</span><Badge count={messages} /></a><a href="/wab/notifications" className="relative grid h-10 w-10 place-items-center rounded-full text-[#006874] hover:bg-[#d7e5e3]" aria-label={`Notifications${notifications ? `, ${notifications} non lues` : ""}`}><span className="material-symbols-outlined">notifications</span><Badge count={notifications} /></a><a href="/wab/profil" className="grid h-9 w-9 overflow-hidden rounded-full border-2 border-white bg-[#d7e5e3]" aria-label="Mon profil">{avatar ? <img src={avatar} alt="Mon profil" className="h-full w-full object-cover" /> : <span className="grid h-full w-full place-items-center text-xs font-bold text-[#006874]">W</span>}</a></nav></div></header>;
}
